### ISSUE TITLE
chore: Add font-synthesis: none

### ISSUE THREAD

**Issue by icidasset** [icidasset/tokono.ma#4]
Avoid faux bold and other styles by defining:
```css
:root {
  font-synthesis: none;
}
```
