### ISSUE TITLE
chore: New syntax for view transitions

### ISSUE THREAD

**Issue by icidasset** [icidasset/tokono.ma#5]
```css
@view-transition {
  navigation: auto;
}
```

https://www.bram.us/2024/05/24/cross-document-view-transitions-for-mpa-you-need-view-transition-to-opt-in-not-the-meta-tag/
